name: naviquake
description: A new Flutter project.
publish_to: 'none'

version: 1.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.0.0
  flutter_timezone: ^2.0.0  # Required for flutter_local_notifications
  cupertino_icons: ^1.0.6
  permission_handler: ^11.1.0
  
  # Other dependencies...
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  flutter_map_tile_caching: ^10.0.0
  path_provider: ^2.1.2
  geolocator: ^11.0.0
  http: ^1.2.0
  audioplayers: ^5.2.1
  flutter_compass: ^0.8.0
  flutter_background_service: ^5.0.5
  shared_preferences: ^2.5.2
  provider: ^6.1.1
  image_picker: ^1.1.2
  simple_gradient_text: ^1.3.0
  flutter_sms_inbox: ^1.0.3

  timezone: any
  path: any
  vibration: ^1.8.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash-logo.png
    - assets/images/warning-splash.png
    - assets/images/image-placeholder.png
    - assets/audio/tts/settings.mp3
    - assets/audio/tts/location.mp3
    - assets/audio/tts/accessibility.mp3
    - assets/audio/tts/almhistory.mp3
    - assets/audio/directions/
    - assets/audio/tts/knowledge1.mp3
    - assets/audio/tts/knowledge2.mp3
    - assets/audio/alarm/alarm.mp3
    - assets/audio/alarm/navigatingnearestroute.mp3

  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf
        - asset: assets/fonts/Product-Sans-Bold.ttf
