name: sms_advanced
description: SMS Advanced plugin for Flutter
version: 1.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.elyudde.sms_advanced
        pluginClass: SmsAdvancedPlugin
